perplexity:
  model: "sonar-deep-research"
  num_companies: 15

company_ranker:
  model: "claude-3-sonnet-20240229"

email_generator:
  model: "claude-3-opus-20240229"

slack:
  channel: "#outreach-bot"

apollo:
  titles:
    - "CTO"
    - "VP Engineering"
    - "Director of DevOps"
    - "Head of Platform"
    - "Infrastructure Manager"
  limit: 3
